#"{" +
#        "  project(slug:\"spring-framework\") {" +
#        "   releases {" +
#        "     version" +
#        "   }"+
#        "  }" +
#        "}";
        
#query projectReleases($slug: ID!) {
#    project(slug: $slug) {
#        releases {
#            version
#        }
#    }
#}
#{" + "	allArticles	{ " + "	id	" + "	}	" + "}

query allArticles {
	allArticles {
		id
	}
}