spring:
  application:
    name: spark-cms
  profiles:
    active: local
server:
  port: 8888
  
---
spring:
  config:
    activate:
      on-profile: "local"
  data:
    mongodb:
      uri: mongodb://localhost:27017/spark-cms

  
