spring:

  application:
    name: spark-cms
  profiles:
    active: local

  servlet:
    multipart:
      location: "Desktop/temp"
server:
  port: 8888
  tomcat:
    basedir: "/tmp"



base:
  file:
    path: "/Users/ranveerkumar/Desktop/files"

graphql:
  extended-scalars: Date
  servlet:
    cors:
      allowed-origins: "*"
#      allowed-origin-patterns: ""
---
spring:
  config:
    activate:
      on-profile: "local"
  data:
    mongodb:
      uri: mongodb://localhost:27017/spark-cms
  
  servlet:
    multipart:
      max-file-size: 10MB





  
